version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: gifty
      POSTGRES_USER: gifty_user
      POSTGRES_PASSWORD: gifty_pass
    ports:
      - "5434:5432"
    volumes:
      - gifty_db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
    ports:
      - "4001:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  gifty_db_data:
